name: "Cached Docker Build"
description: "Use Github Action's cache to store and retrieve docker images"

branding:
  icon: "layers"
  color: "red"

inputs:
  args:
    description: "docker build args"
    required: true
  cache_key:
    description: "Cache key"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"

